# Generated by Django 5.0.6 on 2024-06-18 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Напишите название книги')),
                ('author_name', models.CharField(max_length=100, verbose_name='Напишите имя автора')),
                ('image', models.ImageField(upload_to='programming_blog/', verbose_name='Загрузите фото')),
                ('short_description', models.TextField(verbose_name='Напишите описание')),
                ('data_release', models.DateField(verbose_name='Укажите дату выхода книги')),
                ('genre', models.CharField(choices=[('ФЭНТЕЗИ', 'ФЭНТЕЗИ'), ('ФАНТАСТИКА', 'ФАНТАСТИКА'), ('БОЕВИКИ', 'БОЕВИКИ'), ('ДЕТЕКТИВ', 'ДЕТЕКТИВ'), ('ДРАМА', 'ДРАМА'), ('ХОРРОР', 'ХОРРОР')], max_length=100, verbose_name='Выберите жанр')),
                ('summary', models.FileField(upload_to='summary/', verbose_name='Загрузите  краткое содержание')),
                ('wiki', models.URLField(verbose_name='Вставьте сыллку на википедию')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sliders/')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mark', models.IntegerField(default=5)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_books', to='books.books')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=100)),
                ('tags', models.ManyToManyField(to='books.tags')),
            ],
        ),
    ]
